# Generated by Django 4.0.2 on 2022-03-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inglizcha', models.CharField(max_length=150, verbose_name='Inglizcha')),
                ('uzbekcha', models.CharField(max_length=150, verbose_name="O'zbekcha")),
            ],
        ),
    ]
